theme: minima
title: Lucas' Home
lsi: false
safe: true
incremental: false
highlighter: rouge
# markdown: GFM
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
